### PR TITLE
Stripe webhook payment confirmation

### PR DESCRIPTION
**Pull request by duplxey**
Resolves issue #1.

### CODE REVIEW

**Comment by mjhea0** [comment]
This looks really good @duplxey! Do you think the blog post needs to be updated at the same time?

**Comment by duplxey** [comment]
Thank you.

I don't feel like you need to add all the instructions. You could just leave a message below, saying that they should check out the GitHub repository to see how to use Stripe webhooks in order to confirm payments.

**Comment by mjhea0** [comment]
> Thank you.
> 
> I don't feel like you need to add all the instructions. You could just leave a message below, saying that they should check out the GitHub repository to see how to use Stripe webhooks in order to confirm payments.

I'm happy to pay you to update the post as well as update the post and code for the Flask version as well. Want to reach out over email? michael at testdriven dot io

**Comment by duplxey** [comment]
> I'm happy to pay you to update the post as well as update the post and code for the Flask version as well. Want to reach out over email? michael at testdriven dot io

I've sent you an email.

**Pull request merged**
